### ISSUE TITLE
I love swoopy-drag, but could use some documentation explaining how xVal and yVal are set when first generating an annotation

### ISSUE THREAD

**Issue by palewire** [1wheel/swoopy-drag#13]

**Comment by 1wheel** [comment]
I added a bit to the demo page:

> The x and y functions are called on each annotation to determine its position. In the annotations array here, xVal and yVal properties are the data values of point the annotation refers to. The functions passed to x and y look up these values and encode them as pixel position using scales you've probably set up elsewhere.

`xVal` and `yVal` aren't actually part of the library, just an example for the demo. Perhaps they should be switched to `septalWidth` and `septalHeight` to make it clear that they're referring to a point on the demo chart.

**Comment by 1wheel** [comment]
Updated the text and charts to say `septalWidth` instead of `xVal`. Hopefully that'll make the difference between `.x`, `xScale` and `xVal` clearer. 

The documentation is probably a little too terse -- let me know if you have any other suggestions!

**Comment by palewire** [comment]
Thanks for this addition. Here's one thing I'm not totally clear on and I think might trip up others: After the data has been translated by the d3 "scale", is it correct that the SVG path will then be drawn **relative** to the value's calculated position? 

If that's correct, how can the paths then be best scaled to different screen sizes if the path itself is always a fixed distance from the data value's calculated position?

Am I crazy to imagine that in some cases -- just like the data value -- the annotation's path might need to scale up or down as calculated by the scale?

**Comment by palewire** [comment]
I hope that was English. I'm not the best at talking about this stuff.

**Comment by 1wheel** [comment]
That's right: 

> Since each annotation's position is determined primarily by scales, lines and labels will still point to the correct position when the chart size changes. As the chart shrinks though, the annotations might overlap or cover up data points. To show fewer or differently positioned labels on mobile, you could create multiple annotation arrays for different screen sizes

The *Responsive* section of the docs describe ways of conditionally showing annotations on mobile; I've found that it's less of a problem that I thought it would be.

I think explicitly saying the mark's positions are relative farther up would be helpful.

**Comment by palewire** [comment]
Got it. I think I'm finally beginning to grok it all. Without staying on the therepist's couch too long here, I think my confusion stemmed from my failure to fully grasp the implications of how raw SVG paths work. 

Would it be possible for your incredibly handy drag function to be combined with a dynamic "scaled" drawing mechanism, like what's found in ["swoopyarrows.js"](https://github.com/bizweekgraphics/swoopyarrows)?

**Comment by 1wheel** [comment]
I'm not sure I see a big use case for that. If I needed the whole chart and annotations to shrink uniformly, I would use `transform: scale` or `viewport` along with `non-scaling-stroke`.

**Comment by palewire** [comment]
I guess the use case I imagine is one where user can grab an arrow from the documentation page and slap it in right away, with confidence that it will responsively scale up and down without additional modification.
