### ISSUE TITLE
Click to edit text

### ISSUE THREAD

**Issue by 1wheel** [1wheel/swoopy-drag#8]
http://vis4.net/blog/posts/seven-features-youll-wantin-your-next-charting-tool/

https://bl.ocks.org/mbostock/a84aeb78fea81e1ad806

**Comment by micahstubbs** [comment]
👍

**Comment by 1wheel** [comment]
I've using https://github.com/1wheel/hot-server instead. 

Examples in https://github.com/susielu/d3-annotation links to some implementations of this.
